Individual activity 4
jgcoronadocueva/sleepoutside pull request #29
Opened 2024-10-12 02:37 UTC by ijromerob

2024-10-12 19:58 UTC, jcampos-94 commented on src/test/product.test.js
This needs to be erased.

2024-10-12 20:01 UTC, jcampos-94 commented on src/js/ExternalServices.mjs
It looks good, but a function here or in utils.mjs to delete previous alerts automatically would be helpful.

2024-10-12 20:02 UTC, jcampos-94 requested changes
Added a few comments. Also, the success page doesn't load. I think you forgot to edit vite.config.js

2024-12-04 00:01 UTC, closed without merging

2024-12-04 00:01 UTC, ijromerob commented
this branch was not used